# Generated by Django 5.1.1 on 2024-09-29 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('chef_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chef_full_name', models.CharField(max_length=100)),
                ('chef_details', models.TextField(blank=True)),
                ('chef_img_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=250)),
                ('recipe_description', models.TextField(blank=True)),
                ('recipe_ingredients', models.JSONField(blank=True)),
                ('recipe_duration', models.PositiveIntegerField(blank=True)),
                ('recipe_instructions', models.TextField(blank=True)),
                ('recipe_img_url', models.URLField(blank=True)),
                ('recipe_chef_xref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeBookAPIs.chef')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeBook',
            fields=[
                ('recipe_book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_recipe_xref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeBookAPIs.recipe')),
                ('book_user_xref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeBookAPIs.user')),
            ],
        ),
    ]
